---
title: "STAT545 Assignment 4: Tidy Data and Joins"
output:
  html_document:
    toc: yes
    keep_md: yes
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, echo = FALSE}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(gapminder))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(tsibble))
```

# Part 1 - Univariate Option 1: Comparing Life Expectancies over Time

Full dataframe for reference...

```{r}
gapminder
```

## 1.1: Pivoting Wider to Comapre two Countries

```{r}
gapminder %>% 
  filter(country == "China" | country == "Taiwan") %>% 
  select(country, year, lifeExp) %>% 
  pivot_wider(id_cols = year,
              names_from = country,
              values_from = lifeExp)
```

## 1.2: Plotting with the New Data Layout

```{r}
gapminder %>% 
  filter(country == "China" | country == "Taiwan") %>% 
  select(country, year, lifeExp) %>% 
  pivot_wider(id_cols = year,
              names_from = country,
              values_from = lifeExp) %>% 
  ggplot(aes(Taiwan, China)) +
  geom_point(colour = "dark red") +
  theme_minimal()
```

## 1.3: Pivoting Longer to Return Original Organization
 
```{r}
gapminder %>% 
  filter(country == "China" | country == "Taiwan") %>% 
  select(country, year, lifeExp) %>% 
  pivot_wider(id_cols = year,
              names_from = country,
              values_from = lifeExp) %>% 
  pivot_longer(cols = c(China, Taiwan),
               names_to = "country",
               values_to = "lifeExp")
```

# Part 2 - Multivariate Option 1: Life Expectancy and GDP per Capita over Time

## 2.1: Pivoting Data to the New Layout

```{r}
gapminder %>% 
  filter(country == "China" | country == "Taiwan") %>% 
  select(country, year, lifeExp, gdpPercap) %>% 
  pivot_wider(id_cols = year,
              names_from = country,
              names_sep = "--",
              values_from = c(lifeExp, gdpPercap))
```

